coverage:
  precision: 2
  round: down
  range: "60..75"
  status:
    project:
      default: # default is the status check's name, not default settings
        target: auto
        threshold: "5"

parsers:
  javascript:
    enable_partials: yes
