name: dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'a-novel/tanstack-start-config'
    steps:
      - uses: a-novel-kit/workflows/node-actions/prettier-dependabot@master
        with:
          pat: ${{ secrets.ACTION_PAT }}
      - uses: a-novel-kit/workflows/generic-actions/auto-merge-dependabot@master
        with:
          pull_request: ${{ github.event.pull_request.html_url }}
          pat: ${{ secrets.ACTION_PAT }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
