name: pnpm auto-update

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: a-novel-kit/workflows/node-actions/update-pnpm-version@master
        with:
          pat: ${{ secrets.ACTION_PAT }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
