name: main

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/node-actions/lint-node@master
        with:
          pat: ${{ secrets.ACTION_PAT }}

  build:
    needs:
      - lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: a-novel-kit/workflows/node-actions/build-node@master
        with:
          pat: ${{ secrets.ACTION_PAT }}

  pages:
    if: github.ref == 'refs/heads/master' && success()
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: a-novel-kit/workflows/github-pages-actions/publish-storybook@master
        with:
          build_path: storybook-static
          pat: ${{ secrets.ACTION_PAT }}
